const { test, expect } = require('./fixtures');
const { openApp } = require('./helpers');

// Generated by Sauce Verify from AI Authoring case 6abcef9d85b542d156b3d0e2.
// Journey: Add a todo called 'Buy milk' and verify that 'Buy milk' appears in the todo list. Use exactly the todo names given. This test MUST FAIL if the expected result is not visible or if any error message is shown on the page.
test("Add a todo called 'Buy milk' and verify that 'Buy milk' appears in the todo list. Use exactly the todo names given. This test MUST FAIL if the expected result is not visible or if any error message is shown on the page.", async ({ page }) => {
  await openApp(page);

  await page.getByTestId('new-input').fill("Buy milk");
  await page.getByTestId('add-button').click();
  await expect(page.getByTestId('todo-title')).toHaveText("Buy milk");
});
