const { test, expect } = require('./fixtures');
const { openApp } = require('./helpers');

// Generated by Sauce Verify from AI Authoring case 6abcdf0e59af84bed7d58c41.
// Journey: Add two todos, 'Buy milk' and 'Walk dog', delete 'Buy milk', and check that only 'Walk dog' is left in the list
test("Add two todos, 'Buy milk' and 'Walk dog', delete 'Buy milk', and check that\u2026", async ({ page }) => {
  await openApp(page);

  await page.getByTestId('new-input').fill("Buy milk");
  await page.getByTestId('add-button').click();
  await page.getByTestId('new-input').fill("Walk dog");
  await page.getByTestId('add-button').click();
  await page.locator("[aria-label=\"Delete\\ Buy\\ milk\"]").click();
  await expect(page.getByTestId('todo-title')).toHaveText("Walk dog");
  await expect(page.getByTestId('todo-list')).not.toContainText("Buy milk");
});
