const { test, expect } = require('./fixtures');
const { openApp } = require('./helpers');

// Generated by Sauce Verify from AI Authoring case 6abd020085b542d156b3d0e3.
// Journey: adding a todo puts it in the list
test("adding a todo puts it in the list", async ({ page }) => {
  await openApp(page);

  await page.getByTestId('new-input').fill("Buy milk");
  await page.getByTestId('add-button').click();
  await expect(page.getByTestId('todo-title')).toHaveText("Buy milk");
});
