const { test, expect } = require('./fixtures');
const { openApp } = require('./helpers');

// Generated by Sauce Verify from AI Authoring case 6ac64ef0d5d568e4c7ac3448.
// Journey: page opened → User navigates to a webpage → Clicked BUTTON → add todo — "Buy milk" (on new-form)
test("crash regression: Cannot read properties of undefined (reading 'trim')", async ({ page }) => {
  await openApp(page);

  await page.getByTestId('add-button').click();
  await page.getByTestId('new-input').fill("Buy milk");
  await page.getByTestId('add-button').click();
  await expect(page.getByTestId('toggle').first()).toBeVisible();
  await expect(page.locator("html")).not.toContainText("Cannot read properties of undefined");
});
