const { test, expect } = require('./fixtures');
const { openApp } = require('./helpers');

// Generated by Sauce Verify from AI Authoring case 6abd02543164772a75cda148.
// Journey: delete a complete todo
test("delete a complete todo", async ({ page }) => {
  await openApp(page);

  await page.getByTestId('new-input').fill("Buy groceries");
  await page.getByTestId('add-button').click();
  await page.getByTestId('toggle').click();
  await page.getByTestId('delete').click();
  await expect(page.getByTestId('empty-state')).toHaveText("Nothing here yet.");
});
