const { test, expect } = require('./fixtures');
const { openApp } = require('./helpers');

// Generated by Sauce Verify from AI Authoring case 6abce5233761095cd3070f76.
// Journey: filters show active and completed todos separately
test("filters show active and completed todos separately", async ({ page }) => {
  await openApp(page);

  await page.getByTestId('new-input').fill("Buy groceries");
  await page.getByTestId('add-button').click();
  await page.getByTestId('new-input').fill("Clean room");
  await page.getByTestId('add-button').click();
  await page.locator("[aria-label=\"Complete\\ Clean\\ room\"]").click();
  await page.getByTestId('filter-active').click();
  await expect(page.getByTestId('todo-title')).toHaveText("Buy groceries");
  await page.getByTestId('filter-completed').click();
  await expect(page.getByTestId('todo-title')).toHaveText("Clean room");
});
